### PR TITLE
feat(installer): changed to native download and extraction

### LINKED ISSUE #19: curl is not a preinstalled tool on most build servers
with the new version we get the following error:

```
Error: Unable to locate executable file: 'curl'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
```

as curl is not a default tool on a Windows Server 2016 installation. I would handle the file download in JS

### PR DESCRIPTION
**Pull request by OneCyrus**
changed the file download and extraction to JavaScript to fix #19

### CODE REVIEW

**Comment by MarcBruins** [comment]
Great stuff, have you tested the downloading bits locally?

**Comment by OneCyrus** [comment]
yes, but i‘m not sure how it behaves with the download folder. though i‘ve used the same paths as in your code. is this supposed to land in the working directory?

**Comment by MarcBruins** [comment]
Yes it lands in the working directory. I've the paths are the same then everything shuold be ok. Does `extract-zip` work with non `.zip` extensions?

**Comment by MarcBruins** [comment]
Pushed the new version, should take a few minutes before the new version is out(we should see it here https://marketplace.visualstudio.com/items?itemName=nukeeper.nukeeper#overview)

**Comment by MarcBruins** [comment]
There is still something wrong:

```
No executable found matching command "dotnet-D:\a\_tasks\NuKeeper_e5a17a66-903f-46a9-a9b9-94241bcedc39\0.1.64\src\nukeeper\tools\netcoreapp2.1\any\NuKeeper.dll"
Error: C:\Program Files\dotnet\dotnet.exe failed with return code: 1
Unhandled: Cannot read property 'message' of undefined
```

**Comment by OneCyrus** [comment]
it's not the file download. it's the extraction which needs to await the callback. i have a look

**Comment by MarcBruins** [comment]
right let me know, i can update the extension tomorrow morning.

**Comment by MarcBruins** [comment]
We can also use the old extraction, that works fine and comes from the vsts extension libs

**Pull request merged**
