### PR TITLE
fix for projectScoped vs organisationalScoped feeds

### PR DESCRIPTION
**Pull request by rai69**
This pr contains a fix for #56 

It assumes that the feed variable contains either a single GUID that is the feedId or that the feed variable that contains two GUID's separated by a /. In this case the first GUID represents the projectId and the second represents the feedId. 

The function `getPackageSource` uses the correct url depending on the projectId. It will always return only 1 package source.

### CODE REVIEW

**Comment by AnthonySteele** [comment]
So this PR always generates 1 feed uri, either project scoped or not?

**Comment by rai69** [comment]
@AnthonySteele That is correct. Perhaps that there are projects that need multiple feeds, but the AzureDevOps Settings of the NuKeeper Task only allows one feed.

**Comment by rai69** [comment]
The feeds in Azure DevOps can have multiple upstream sources. If needed someone could create a projectfeed and include its organisational feed as an upstream source.

**Comment by Jabra0614** [comment]
@AnthonySteele Thank you very much.  Do we know about when this will be pushed to the Market place for install?

**Comment by rai69** [comment]
@AnthonySteele I suspect that @MarcBruins has the information to publish this to the marketplace?

**Comment by AnthonySteele** [comment]
I will have a look at the build & publish pipelines on the weekend.

**Comment by rai69** [comment]
@AnthonySteele That would be great. If I can be of any help, just let me now.

**Comment by Jabra0614** [comment]
@AnthonySteele any luck?

**Comment by rai69** [comment]
@AnthonySteele @MarcBruins Any progres to report?

**Comment by MarcBruins** [comment]
Sorry guys, I was a bit busy with other stuff and don't have a lot of time to contribute to this project at the moment. I'll have a look at the PR this week and make a new release.

**Comment by MarcBruins** [comment]
@AnthonySteele also has the credentials but you'll have to run a few commands to make it work and there is no pipelines in place right now to push this to the market automatically, if anyone wants to work on that feel free. 

My collegeau @jessehouwing has made these tasks that can help: https://marketplace.visualstudio.com/items?itemName=jessehouwing.jessehouwing-vsts-extension-tasks

**Comment by jessehouwing** [comment]
https://www.github.com/microsoft/azure-devops-extension-tasks/tree/main/azure-pipelines.yml

Should do the trick as a template pipeline...

**Pull request merged**
